function writeBladed(fileID, u, v, w , x, y, z, U)
% writeBladed writes a wind-data file in Bladed style. The writing of the
% file is separated by this function from opening the file to separate
% agnostic fileIO from formatting the content of the file. Nevertheless,
% this function uses the fileID and writes directly to the file.
%
%   Syntax
%     writeBladed(fileID, u, v, w , x, y, z, U)
%
%   Input arguments
%     fileID - File identifier of an opened file to which to write the data
%     [u, v, w, x, y, z] - Wind data generated by bladedStyle.m, needed to
%     create Bladed style wind file
%     U - 10-Minute average wind speed
%
%   Output
%     [-]
%
%   Behaviour
%     The input wind data and the 10-minute average wind speed are printed
%     to file according to the Bladed wind-file format. Several simple
%     calculations are done to transform the input data to the required
%     data for the wind file.
%
%   Called by
%     FileIOClass.writeBladedFile

% ToDo: This function needs further commenting. The person who wrote it is
% no longer available for the development of FASTTool.

[Nx,Ny,Nz]=size(u);

New=-99;
fwrite(fileID,New,'int16');

Spec=3;
fwrite(fileID,Spec,'uint16');

delta_x=x(2)-x(1);
% BLADED: first element at right bottom corner, i.e. maximum y
delta_y=-(y(2)-y(1));
delta_z=z(2)-z(1);

fwrite(fileID,delta_z,'float32');
fwrite(fileID,delta_y,'float32');
fwrite(fileID,delta_x,'float32');

Nx2=Nx/2;
fwrite(fileID,Nx2,'uint32');

fwrite(fileID,U,'float32');

Lux=70.7;
Luy=Lux/2;
Luz=Lux/2;
fwrite(fileID,Luz,'float32');
fwrite(fileID,Luy,'float32');
fwrite(fileID,Lux,'float32');

fwrite(fileID,1,'uint32');
Seed=1;
fwrite(fileID,Seed,'uint32');

fwrite(fileID,Nz,'uint32');
fwrite(fileID,Ny,'uint32');

% length scales
fwrite(fileID,100,'float32');
fwrite(fileID,100,'float32');
fwrite(fileID,100,'float32');
fwrite(fileID,100,'float32');
fwrite(fileID,100,'float32');
fwrite(fileID,100,'float32');

Nplane=Ny*Nz*3;
Ind1=1:3:Nplane;
Ind2=2:3:Nplane;
Ind3=3:3:Nplane;
% scaling
u=u*1000;
v=v*1000;
w=w*1000;
uvw=zeros(1,Nplane);
for i=1:Nx
   uu=reshape(u(i,:,:),1,Ny*Nz);
   vv=reshape(v(i,:,:),1,Ny*Nz);
   ww=reshape(w(i,:,:),1,Ny*Nz);
   uvw(Ind1)=uu;
   uvw(Ind2)=vv;
   uvw(Ind3)=ww;
   fwrite(fileID,uvw,'int16'); 
end

